// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Uganda.AdministrativeUnits.Infrastructure.Persistence;

#nullable disable

namespace Uganda.AdministrativeUnits.Infrastructure.Migrations
{
    [DbContext(typeof(AdministrativeUnitsDbContext))]
    partial class AdministrativeUnitsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Constituency", b =>
                {
                    b.Property<string>("FullCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Breadcrumb")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("DistrictCode")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("FullCode");

                    b.HasIndex("DistrictCode");

                    b.HasIndex("Name");

                    b.ToTable("Constituencies", (string)null);
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.DatasetMeta", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CorrectionsApplied")
                        .HasColumnType("int");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateOnly>("PublishedOn")
                        .HasColumnType("date");

                    b.Property<string>("SourceNote")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("DatasetMeta", (string)null);
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.District", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Breadcrumb")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("FullCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Code");

                    b.HasIndex("FullCode")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Parish", b =>
                {
                    b.Property<string>("FullCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Breadcrumb")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("SubcountyFullCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("FullCode");

                    b.HasIndex("Name");

                    b.HasIndex("SubcountyFullCode");

                    b.ToTable("Parishes", (string)null);
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Subcounty", b =>
                {
                    b.Property<string>("FullCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Breadcrumb")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("ConstituencyFullCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("FullCode");

                    b.HasIndex("ConstituencyFullCode");

                    b.HasIndex("Name");

                    b.ToTable("Subcounties", (string)null);
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Village", b =>
                {
                    b.Property<string>("FullCode")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Breadcrumb")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ParishFullCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("FullCode");

                    b.HasIndex("Name");

                    b.HasIndex("ParishFullCode");

                    b.ToTable("Villages", (string)null);
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Constituency", b =>
                {
                    b.HasOne("Uganda.AdministrativeUnits.Domain.Entities.District", "District")
                        .WithMany("Constituencies")
                        .HasForeignKey("DistrictCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Parish", b =>
                {
                    b.HasOne("Uganda.AdministrativeUnits.Domain.Entities.Subcounty", "Subcounty")
                        .WithMany("Parishes")
                        .HasForeignKey("SubcountyFullCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subcounty");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Subcounty", b =>
                {
                    b.HasOne("Uganda.AdministrativeUnits.Domain.Entities.Constituency", "Constituency")
                        .WithMany("Subcounties")
                        .HasForeignKey("ConstituencyFullCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Constituency");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Village", b =>
                {
                    b.HasOne("Uganda.AdministrativeUnits.Domain.Entities.Parish", "Parish")
                        .WithMany("Villages")
                        .HasForeignKey("ParishFullCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parish");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Constituency", b =>
                {
                    b.Navigation("Subcounties");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.District", b =>
                {
                    b.Navigation("Constituencies");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Parish", b =>
                {
                    b.Navigation("Villages");
                });

            modelBuilder.Entity("Uganda.AdministrativeUnits.Domain.Entities.Subcounty", b =>
                {
                    b.Navigation("Parishes");
                });
#pragma warning restore 612, 618
        }
    }
}
