<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <NoWarn>$(NoWarn);CA1707;CA1859;CA1861</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="8.8.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Uganda.AdministrativeUnits.Api\Uganda.AdministrativeUnits.Api.csproj" />
    <ProjectReference Include="..\..\src\Uganda.AdministrativeUnits.Application\Uganda.AdministrativeUnits.Application.csproj" />
    <ProjectReference Include="..\..\src\Uganda.AdministrativeUnits.Contracts\Uganda.AdministrativeUnits.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Uganda.AdministrativeUnits.Infrastructure\Uganda.AdministrativeUnits.Infrastructure.csproj" />
  </ItemGroup>

</Project>
